version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: indexer
    volumes:
      - mongo_data:/data/db

  indexer:
    build: .
    container_name: indexer
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  mongo_data: 